# Update these values for your local MySQL environment.
db.url=jdbc:mysql://localhost:3306/ec_site?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
# db.url=jdbc:mysql://localhost:3306/ec_site?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo&characterEncoding=utf8

db.user=ec_user
db.password=ec_password
