-- Run this script after connecting to the target database (ec_site).

CREATE TABLE IF NOT EXISTS goods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price INT NOT NULL,
  category VARCHAR(64) NOT NULL,
  image_url VARCHAR(1024),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_goods_code ON goods (code);
CREATE INDEX IF NOT EXISTS idx_goods_category ON goods (category);

CREATE TABLE IF NOT EXISTS stocks (
  good_id BIGINT PRIMARY KEY,
  quantity INT NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_stocks_goods FOREIGN KEY (good_id) REFERENCES goods (id)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  last_name VARCHAR(32) NOT NULL,
  first_name VARCHAR(32) NOT NULL,
  address VARCHAR(255),
  card_number_last4 VARCHAR(4),
  card_brand VARCHAR(32),
  card_exp_month SMALLINT,
  card_exp_year SMALLINT,
  card_name VARCHAR(255),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (email);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  ordered_at TIMESTAMP NOT NULL,
  total_amount INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_orders_users FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_orders_user ON orders (user_id);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  good_id BIGINT NOT NULL,
  unit_price INT NOT NULL,
  quantity INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_order_items_goods FOREIGN KEY (good_id) REFERENCES goods (id)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_good ON order_items (good_id);
